---
# Per environment values which override defaults in hmpps-electronic-monitoring-crime-matching-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: electronic-monitoring-crime-matching-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://electronic-monitoring-crime-matching-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    EM_CRIME_MATCHING_API_URL: ""

    # OS Maps cache configuration (applies to vector tiles and assets)
    OS_MAPS_TILE_CACHE_EXPIRY: "604800" # 7 days

generic-prometheus-alerts:
  alertSeverity: na
